env:
  global:
    FIREBASE_TOKEN:
      secure: F5oej9hJtcQBxXlJ4UctJJyQNLIgT0UGXEiAaXV0ze7BoysgB5zNXCTamSOxY0zeEA81D/qdJ26tD9j5mBnZoDClf2WAdqEREPybYwKGlXRElsr73HBkv3LHDkjO0JBf5vRNpT2ojq7ZVcHlnbrjqGWD2qYQza/BkyL/GJa7HlD9VplUnpvjkgcmBcVqDlnWwo5kLzs+S+wY2h2mhzuapZLbjhL27GXGg6Vgtzd832wj9V8mO3P05XnZy+qKg5WQUNiuB6jVUyiAGI+rGDVImsQa3B1liKhhEAhlff1YEyU7E6X1GwEowk5kjKbv8/IQqOzTW9sp+MLEM5DFO6FIhzbEqd/ho36c7vH32pRiRTkHDH4BN/lAhtkaRgHLMVi/AggCxvY0/z5fpyn/g2l7Y+uuYRSgr+eqDJk8WRVyBjOifEsnPT0SZxS3fkIlK93m/xdjlFmRWS/V0gwFt/OMGJ6vgK/WqnB/PDgOryKZeRUGmOHBwoO9/X8jmSEOMF7+YjogNEnznfYdCv47H7zxcDA3lup0MwmU9Ly/sVO5tkm7Uyt3aGhRQ0tRH2Nf6cYS7AMoa5pFVlkxB8wO7PC5S6LWoHoSIdcoZt2taGFUcL5J9bqsAm/U4sVf2jUyhCFTRk7tkw6+kx0hFtNwkbvdO7g7AiQlFMD4b37tbPIdCac=

language: node_js
node_js: 8
script:
  - echo "Deploy!!"
install:
  - npm install
after_success:
  - npx firebase deploy --token $FIREBASE_TOKEN