language: node_js
node_js: 8
script:
- echo "Deploy!!"
install:
- npm install
after_success:
- npx firebase deploy --token $FIREBASE_TOKEN
env:
  global:
    secure: R5QMBONdtuz83AtrhtsJ+yqWP8ymvjpUl50EcTT71IimtNHC2HpOaG1xDV29Z1IKucbVDJFA+a7WDSpgPCXfpox3wCfQg7ItAq3ZYzA59NuQdllxo48ldBWZHj/07aqpnZZdSiknBnM0+EPKcfbDIFHX0Hb0IHoHLudFc7gkg4JKwZSisvjfFH7r+JG2mp/q5S6aDz+pUmagTpwFFlWXIbqGD5j6Vqiqek8mGH5KapnF1xPhiUd77qZsiV2TKB4e72WKrhQPEThicTiyNry97GHPPzcLRvbhDX68Cf5Xn1CdSGHt8UJhynd6U6d/mctT0k7HWHiPMWzwIIbNVi9+l+59pmDiV3/y7lDdUHguak8GAOImH8ch0HrE4SWEpPbq+djb6CLy44Excx54Naad9HHMbhQXlG37ZLTXqFMnVvVVCUDgRj7kOGNAddsKF7Y+/4DbEkF6ElY2FJ9lvA12a9X70tZA3c8igPs5nzs1z23LCTWJylKLx6+MYTngs503iTQ+FLAoGiQTigptGhwLukQRhueFLbaudGfMrZPFs1GIAOi2rbEP1efZEmJ19j9MwRfUUg1Zztk9ijdAag4i7TUeT+GaxS9h7pizf+V5lPQLYLhF7UVuaqbtxsB/FsvtSUXtmBQIyYPIbfHaQsnFaA+0+tp2vYNBMgpJQOOlfk8=
